"""Stage 3: classify the full dataset with the saved fine-tuned model."""

from __future__ import annotations

import argparse
from pathlib import Path

from tqdm import tqdm

from sentiment_workflow.config.paths import (
    BASE_CLASSIFIED_NEWS_PATH,
    FINETUNED_CLASSIFIED_NEWS_PATH,
    FINETUNED_MODEL_HF_REPO,
    SECONDARY_MODEL_HF_REPO,
)
from sentiment_workflow.data.records import (
    finalize_records_file,
    load_records,
    load_seen_values,
    open_checkpoint_handle,
    write_jsonl_record,
)
from sentiment_workflow.ml.inference import (
    describe_device,
    extract_calibration_parameters,
    format_calibration_parameters,
    load_sequence_classifier,
    load_training_metadata,
    predict_scores,
    predict_scores_blended,
)

BATCH_SIZE = 32


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Re-classify the full dataset using the saved fine-tuned model."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=BASE_CLASSIFIED_NEWS_PATH,
        help="Input JSONL generated by the base classifier",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=FINETUNED_CLASSIFIED_NEWS_PATH,
        help="Output JSONL for the fine-tuned predictions",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    print(f"Loading fine-tuned model: {FINETUNED_MODEL_HF_REPO}")
    tokenizer, model, device = load_sequence_classifier(FINETUNED_MODEL_HF_REPO)
    print(f"Device: {describe_device(device)}")

    training_metadata = load_training_metadata(hf_repo=FINETUNED_MODEL_HF_REPO)
    calibration_parameters = extract_calibration_parameters(training_metadata)
    if calibration_parameters is None:
        raise ValueError(
            "No saved calibration parameters were found. Run train-finetuned-model to persist the calibrated champion before classification."
        )

    print(
        "Using saved calibration parameters: "
        + format_calibration_parameters(calibration_parameters)
    )

    ensemble_models = [(tokenizer, model, device)]
    if training_metadata.get("ensemble_mode"):
        print(f"Loading secondary model: {SECONDARY_MODEL_HF_REPO}")
        tok_s, mdl_s, dev_s = load_sequence_classifier(SECONDARY_MODEL_HF_REPO)
        ensemble_models.append((tok_s, mdl_s, dev_s))
        print(f"Ensemble: {len(ensemble_models)} models will be blended.")

    print(f"\nReading source records from: {args.source}")
    if not args.source.exists():
        raise FileNotFoundError(
            f"{args.source} not found. Run main.py classify-base-model first."
        )

    records = load_records(args.source)
    print(f"Total records: {len(records):,}")

    already_done = load_seen_values(args.output, "url")
    if already_done:
        print(f"Checkpoint: {len(already_done):,} records already done, resuming...")

    remaining = [record for record in records if record.get("url") not in already_done]
    print(f"Records to classify: {len(remaining):,}")

    total_batches = (len(remaining) + BATCH_SIZE - 1) // BATCH_SIZE
    with open_checkpoint_handle(args.output) as handle:
        for start in tqdm(
            range(0, len(remaining), BATCH_SIZE),
            total=total_batches,
            desc="Classifying",
        ):
            batch_records = remaining[start : start + BATCH_SIZE]
            batch_texts = [
                str(record.get("sentiment_text") or "") for record in batch_records
            ]
            if len(ensemble_models) > 1:
                predictions = predict_scores_blended(
                    batch_texts,
                    ensemble_models,
                    calibration_parameters=calibration_parameters,
                    batch_size=BATCH_SIZE,
                )
            else:
                predictions = predict_scores(
                    batch_texts,
                    tokenizer,
                    model,
                    device,
                    calibration_parameters=calibration_parameters,
                    batch_size=BATCH_SIZE,
                )

            for record, predicted_label, scores in zip(
                batch_records,
                predictions.predicted_labels,
                predictions.score_dicts,
            ):
                write_jsonl_record(
                    handle,
                    {
                        "source": record.get("source"),
                        "url": record.get("url"),
                        "title": record.get("title"),
                        "description": record.get("description"),
                        "published_at": record.get("published_at"),
                        "week_key": record.get("week_key"),
                        "sentiment_text": record.get("sentiment_text"),
                        "predicted_label": predicted_label,
                        "score_positive": scores.get("POSITIVE", 0.0),
                        "score_negative": scores.get("NEGATIVE", 0.0),
                        "score_neutral": scores.get("NEUTRAL", 0.0),
                    },
                )

    finalize_records_file(args.output)
    print(f"\nDone. Results saved to: {args.output}")


if __name__ == "__main__":
    main()
