"""Stage 3: classify the full dataset with the saved fine-tuned model."""

from __future__ import annotations

import argparse
from pathlib import Path

from tqdm import tqdm

from classification_workflow.config.paths import (
    BASE_CLASSIFIED_NEWS_PATH,
    ENSEMBLE_MODEL_DIRS,
    FINETUNED_CLASSIFIED_NEWS_PATH,
)
from classification_workflow.data.records import (
    finalize_records_file,
    load_records,
    load_seen_values,
    open_checkpoint_handle,
    write_jsonl_record,
)
from classification_workflow.ml.inference import (
    describe_device,
    load_sequence_classifier,
    load_training_metadata,
    predict_scores,
    predict_scores_blended,
)

BATCH_SIZE = 32


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Re-classify the full dataset using the saved fine-tuned model."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=BASE_CLASSIFIED_NEWS_PATH,
        help="Input JSONL generated by the base classifier",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=FINETUNED_CLASSIFIED_NEWS_PATH,
        help="Output JSONL for the fine-tuned predictions",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the output JSONL instead of resuming from the existing checkpoint",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    training_metadata = load_training_metadata()
    model_dirs = [
        Path(path)
        for path in (training_metadata or {}).get(
            "ensemble_model_dirs",
            [str(path) for path in ENSEMBLE_MODEL_DIRS],
        )
    ]

    ensemble_models = []
    for model_dir in model_dirs:
        print(f"Loading fine-tuned model: {model_dir}")
        tokenizer, model, device = load_sequence_classifier(model_dir)
        ensemble_models.append((tokenizer, model, device))
        print(f"Device: {describe_device(device)}")

    if not ensemble_models:
        raise ValueError("No fine-tuned model directories were configured.")
    print(f"Ensemble: {len(ensemble_models)} models will be averaged with identity argmax.")

    print(f"\nReading source records from: {args.source}")
    if not args.source.exists():
        raise FileNotFoundError(
            f"{args.source} not found. Run main.py classify-base-model first."
        )

    records = load_records(args.source)
    print(f"Total records: {len(records):,}")

    if args.force and args.output.exists():
        args.output.unlink()
        print(f"Force mode: removed previous output file: {args.output}")

    already_done = load_seen_values(args.output, "url")
    if already_done:
        print(f"Checkpoint: {len(already_done):,} records already done, resuming...")

    remaining = [record for record in records if record.get("url") not in already_done]
    print(f"Records to classify: {len(remaining):,}")

    total_batches = (len(remaining) + BATCH_SIZE - 1) // BATCH_SIZE
    with open_checkpoint_handle(args.output) as handle:
        for start in tqdm(
            range(0, len(remaining), BATCH_SIZE),
            total=total_batches,
            desc="Classifying",
        ):
            batch_records = remaining[start : start + BATCH_SIZE]
            batch_texts = [
                str(record.get("sentiment_text") or "") for record in batch_records
            ]
            if len(ensemble_models) > 1:
                predictions = predict_scores_blended(
                    batch_texts,
                    ensemble_models,
                    batch_size=BATCH_SIZE,
                )
            else:
                tokenizer, model, device = ensemble_models[0]
                predictions = predict_scores(
                    batch_texts,
                    tokenizer,
                    model,
                    device,
                    batch_size=BATCH_SIZE,
                )

            for record, predicted_label, scores in zip(
                batch_records,
                predictions.predicted_labels,
                predictions.score_dicts,
            ):
                write_jsonl_record(
                    handle,
                    {
                        "source": record.get("source"),
                        "url": record.get("url"),
                        "title": record.get("title"),
                        "description": record.get("description"),
                        "published_at": record.get("published_at"),
                        "week_key": record.get("week_key"),
                        "sentiment_text": record.get("sentiment_text"),
                        "predicted_label": predicted_label,
                        "score_positive": scores.get("POSITIVE", 0.0),
                        "score_negative": scores.get("NEGATIVE", 0.0),
                        "score_neutral": scores.get("NEUTRAL", 0.0),
                    },
                )

    finalize_records_file(args.output)
    print(f"\nDone. Results saved to: {args.output}")


if __name__ == "__main__":
    main()
