"""Generate weekly sentiment scores from fine-tuned article predictions."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from classification_workflow.config.paths import (
    FINETUNED_CLASSIFIED_NEWS_PATH,
    WEEKLY_SENTIMENT_SCORES_PATH,
)

LABELS = ["Muito Negativo", "Negativo", "Neutro", "Positivo", "Muito Positivo"]
CLASSIFICATION_BINS = {
    "weekly_score": [-np.inf, -0.15, -0.05, 0.05, 0.15, np.inf],
    "ma4_score": [-np.inf, -0.09, -0.03, 0.03, 0.09, np.inf],
    "ma13_score": [-np.inf, -0.06, -0.02, 0.02, 0.06, np.inf],
    "ma52_score": [-np.inf, -0.03, -0.01, 0.01, 0.03, np.inf],
}
EXPORT_COLUMNS = [
    "week_key",
    "week_start",
    "weekly_score",
    "ma4_score",
    "ma13_score",
    "ma52_score",
    "weekly_classification",
    "ma4_classification",
    "ma13_classification",
    "ma52_classification",
]


def week_key_to_date(week_key: str) -> pd.Timestamp:
    year, week = week_key.split("-W")
    return pd.Timestamp.fromisocalendar(int(year), int(week), 1)


def prepare_sentiment_frame(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.copy()
    score_sum = (
        frame["score_positive"] + frame["score_negative"] + frame["score_neutral"]
    )
    frame["pos"] = frame["score_positive"] / score_sum
    frame["neg"] = frame["score_negative"] / score_sum
    frame["neu"] = frame["score_neutral"] / score_sum
    frame["confidence"] = frame.apply(
        lambda row: {
            "POSITIVE": row["pos"],
            "NEGATIVE": row["neg"],
            "NEUTRAL": row["neu"],
        }[row["predicted_label"]],
        axis=1,
    )
    frame["net_score"] = frame["pos"] - frame["neg"]
    frame["year"] = frame["week_key"].str[:4].astype(int)
    frame.loc[frame["year"] == 2026, "year"] = 2025
    return frame


def load_prediction_frame(source_path: Path) -> pd.DataFrame:
    if not source_path.exists():
        raise FileNotFoundError(
            f"{source_path} not found. Run main.py classify-finetuned-model first."
        )

    raw_frame = pd.read_json(source_path, lines=True)
    frame = prepare_sentiment_frame(raw_frame)
    frame["published_at"] = pd.to_datetime(
        frame["published_at"], format="ISO8601", utc=True
    )
    frame["week_num"] = frame["week_key"].str.extract(r"W(\d+)").astype(int)
    frame["week_start"] = frame["week_key"].map(week_key_to_date)
    return frame[frame["year"].between(2016, 2025)].copy().reset_index(drop=True)


def build_weekly_sentiment_scores(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.copy()
    frame["contrib"] = frame["pos"] - frame["neg"]

    weekly_scores = (
        frame.groupby(["week_key", "week_start"])
        .agg(raw_score=("contrib", "mean"))
        .reset_index()
        .sort_values("week_start")
        .reset_index(drop=True)
    )

    historical_mean = weekly_scores["raw_score"].mean()
    weekly_scores["weekly_score"] = weekly_scores["raw_score"] - historical_mean
    weekly_scores["ma4_score"] = (
        weekly_scores["weekly_score"].rolling(4, center=True, min_periods=2).mean()
    )
    weekly_scores["ma13_score"] = (
        weekly_scores["weekly_score"].rolling(13, center=True, min_periods=6).mean()
    )
    weekly_scores["ma52_score"] = (
        weekly_scores["weekly_score"].rolling(52, center=True, min_periods=26).mean()
    )

    for column, bins in CLASSIFICATION_BINS.items():
        classification_column = column.replace("_score", "_classification")
        weekly_scores[classification_column] = pd.cut(
            weekly_scores[column], bins=bins, labels=LABELS
        )

    return weekly_scores


def generate_weekly_sentiment_scores(source_path: Path, output_path: Path) -> pd.DataFrame:
    frame = load_prediction_frame(source_path)
    weekly_scores = build_weekly_sentiment_scores(frame)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    weekly_scores[EXPORT_COLUMNS].to_csv(output_path, index=False, float_format="%.6f")
    return weekly_scores


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate weekly sentiment scores from fine-tuned predictions."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=FINETUNED_CLASSIFIED_NEWS_PATH,
        help="Input JSONL generated by classify-finetuned-model.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=WEEKLY_SENTIMENT_SCORES_PATH,
        help="Output CSV for weekly sentiment scores.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    weekly_scores = generate_weekly_sentiment_scores(args.source, args.output)
    print(f"Saved {len(weekly_scores)} weeks -> {args.output}")


if __name__ == "__main__":
    main()